spring:
  # 数据源配置
  datasource:
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: X5&g$qA8#2mN@9sJy3*6pR$1zT!0vFbC
    # 连接数据库的url，不同数据库不一样
    url: jdbc:mysql://124.222.255.129:3306/datasource?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    # 这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  # 对应resources下的目录
  mapper-locations: classpath:mapper/*.xml
  # 指向实体类的包名
  type-aliases-package: com.fclever.mybatis.part3.mybatis.entity