# 国际化
spring:
  messages:
    basename: i18n/login
# 数据源配置
  datasource:
    # 连接数据库的用户名
    username: root
    # 连接数据库的密码
    password: X5&g$qA8#2mN@9sJy3*6pR$1zT!0vFbC
    # 连接数据库的url，不同数据库不一样
    url: jdbc:mysql://124.222.255.129:3306/datasource?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    # 这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时，默认0
    initialSize: 5
    # 最小连接池数量
    minIdle: 5
    # 最大连接池数量
    maxActive: 20
    # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    # 有两个含义：
    #   1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
    #   2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    # 连接保持空闲而不被驱逐的最小时间
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
    validationQuery: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址： https://mvnrepository.com/artifact/log4j/log4j
    # 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #   监控统计用的filter:stat
    #   日志用的filter:log4j
    #   防御sql注入的filter:wall
    filters: stat,wall,log4j
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
# 使用---分隔符，您可以将配置按照不同的部分进行组织和管理
# 多数据源测试
---
spring:
  datasource:
    local:
      username: root
      password: X5&g$qA8#2mN@9sJy3*6pR$1zT!0vFbC
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://124.222.255.129:3306/datasource?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    remote:
      username: root
      password: X5&g$qA8#2mN@9sJy3*6pR$1zT!0vFbC
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://124.222.255.129:3307/datasource?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
